# Generated by Django 4.0.6 on 2022-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_remove_product_color_delete_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Mavjud emas', 'Mavjud emas')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
