# Generated by Django 4.0.6 on 2022-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_filter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.CharField(choices=[('kg', 'kg'), ('dona', 'dona'), ('pors', 'pors')], default=0, max_length=200),
        ),
    ]
