# Generated by Django 4.0.6 on 2022-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0006_alter_product_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quant',
            field=models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('pors', 'pors'), ('dona', 'dona')], default=0, max_length=200),
        ),
    ]
